# Generated by Django 4.2 on 2023-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_login_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_level', models.TextField(blank=True, null=True)),
                ('max_health', models.TextField(blank=True, null=True)),
                ('cur_health', models.TextField(blank=True, null=True)),
                ('coins', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'save',
                'managed': False,
            },
        ),
    ]
